<?php

namespace Dtc\QueueBundle\Entity;

use Dtc\QueueBundle\Model\Job as BaseJob;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="job", indexes={@ORM\Index(name="job_crc_hash_idx", columns={"crcHash","status"}),
 *                  @ORM\Index(name="job_priority_idx", columns={"priority","whenAt"}),
 *                  @ORM\Index(name="job_when_idx", columns={"whenAt","locked"}),
 *                  @ORM\Index(name="job_status_idx", columns={"status","locked","whenAt"})})
 */
class Job extends BaseJob
{
    /**
     * @ORM\Column(type="bigint")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $workerName;

    /**
     * @ORM\Column(type="string")
     */
    protected $className;

    /**
     * @ORM\Column(type="string")
     */
    protected $method;

    /**
     * @ORM\Column(type="string")
     */
    protected $status;

    /**
     * @ORM\Column(type="text")
     */
    protected $args;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $batch;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $locked;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $lockedAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $priority;

    /**
     * @ORM\Column(type="string")
     */
    protected $crcHash;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $whenAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $expiresAt;

    /**
     * When the job started.
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $startedAt;

    /**
     * When the job finished.
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $finishedAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $elapsed;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $message;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $maxDuration;

    public function setArgs($args)
    {
        $args = serialize($args);
        parent::setArgs($args); // TODO: Change the autogenerated stub
    }

    public function getArgs()
    {
        $args = parent::getArgs();

        return unserialize($args);
    }
}
